import type { RepoContext, RepoMode } from "../types";

const NEXT_CONFIG_PATHS = [
  "next.config.ts",
  "next.config.js",
  "next.config.mjs",
  "next.config.cjs",
];

const HTML_AT_ROOT_PATHS = ["index.html", "public/index.html"];

// Error / status pages — generated by frameworks like Rails, Django,
// Phoenix. They're never the canonical "homepage" and shouldn't trigger
// HTML mode on their own.
const ERROR_PAGE_REGEX = /(?:^|\/)(?:[345]\d\d|maintenance|offline|coming-soon)\.html$/i;

const SERVER_RENDERED_MARKERS = [
  "Gemfile", // Ruby / Rails
  "config/application.rb", // Rails
  "manage.py", // Django
  "mix.exs", // Elixir / Phoenix
  "artisan", // Laravel
  "composer.json", // PHP
  "go.mod", // Go (Gin, Echo, etc.)
  "Cargo.toml", // Rust (Actix, Axum, etc.)
];

function isContentHtml(path: string): boolean {
  if (!path.endsWith(".html")) return false;
  if (path.includes("/node_modules/")) return false;
  if (path.includes("/.next/") || path.includes("/dist/") || path.includes("/build/")) return false;
  if (ERROR_PAGE_REGEX.test(path)) return false;
  return true;
}

export async function detectRepoMode(ctx: RepoContext): Promise<RepoMode> {
  // Next.js: explicit config or "next" dependency.
  if (ctx.hasAnyPath(NEXT_CONFIG_PATHS)) return "next";

  const pkg = await ctx.getFile("package.json");
  if (pkg) {
    try {
      const parsed = JSON.parse(pkg) as {
        dependencies?: Record<string, string>;
        devDependencies?: Record<string, string>;
      };
      if (parsed.dependencies?.next || parsed.devDependencies?.next) return "next";
    } catch {
      // ignore malformed package.json
    }
  }

  // Server-rendered backends (Rails, Django, Phoenix, Laravel, Go, Rust):
  // even if they ship error-page HTML in /public, the actual rendered HTML
  // is server-side and not in the repo. Treat as unknown so only
  // file-presence rules (robots.txt, sitemap.xml) fire.
  if (ctx.hasAnyPath(SERVER_RENDERED_MARKERS)) return "unknown";

  // Static HTML mode requires a real homepage candidate.
  if (ctx.hasAnyPath(HTML_AT_ROOT_PATHS)) return "html";
  for (const path of ctx.tree.keys()) {
    if (isContentHtml(path)) return "html";
  }

  return "unknown";
}
